const types = {
  redux: {
    GET_EXPENSES_SUCCESS: 'EXPENSES.REDUX.GET_EXPENSES_SUCCESS',
    GET_EXPENSES_FAILURE: 'EXPENSES.REDUX.GET_EXPENSES_FAILURE',
    GET_EXPENSES_LOADING: 'EXPENSES.REDUX.GET_EXPENSES_LOADING',

    GET_TAGS_SUCCESS: 'EXPENSES.REDUX.GET_TAGS_SUCCESS',
    GET_TAGS_FAILURE: 'EXPENSES.REDUX.GET_TAGS_FAILURE',
    GET_TAGS_LOADING: 'EXPENSES.REDUX.GET_TAGS_LOADING',

    GET_SUMMARY_SUCCESS: 'EXPENSES.REDUX.GET_SUMMARY_SUCCESS',
    GET_SUMMARY_FAILURE: 'EXPENSES.REDUX.GET_SUMMARY_FAILURE',
    GET_SUMMARY_LOADING: 'EXPENSES.REDUX.GET_SUMMARY_LOADING',
  },
  saga: {
    GET_EXPENSES: 'EXPENSES.SAGA.GET_EXPENSES',
    GET_TAGS: 'EXPENSES.SAGA.GET_TAGS',
    GET_SUMMARY: 'EXPENSES.SAGA.GET_SUMMARY',
  },
}

export default types