const types = {
  redux: {
    GET_INCOMES_SUCCESS: 'INCOMES.REDUX.GET_INCOMES_SUCCESS',
    GET_INCOMES_FAILURE: 'INCOMES.REDUX.GET_INCOMES_FAILURE',
    GET_INCOMES_LOADING: 'INCOMES.REDUX.GET_INCOMES_LOADING',

    POST_ADD_INCOMES_SUCCESS: 'INCOMES.REDUX.POST_ADD_INCOMES_SUCCESS',
    POST_ADD_INCOMES_FAILURE: 'INCOMES.REDUX.POST_ADD_INCOMES_FAILURE',
    POST_ADD_INCOMES_LOADING: 'INCOMES.REDUX.POST_ADD_INCOMES_LOADING',

    POST_ADD_KANTONG_SUCCESS: 'INCOMES.REDUX.POST_ADD_KANTONG_SUCCESS',
    POST_ADD_KANTONG_FAILURE: 'INCOMES.REDUX.POST_ADD_KANTONG_FAILURE',
    POST_ADD_KANTONG_LOADING: 'INCOMES.REDUX.POST_ADD_KANTONG_LOADING', 

    GET_SUMMARY_INCOMES_SUCCESS: 'INCOMES.REDUX.GET_SUMMARY_INCOMES_SUCCESS',
    GET_SUMMARY_INCOMES_FAILURE: 'INCOMES.REDUX.GET_SUMMARY_INCOMES_FAILURE',
    GET_SUMMARY_INCOMES_LOADING: 'INCOMES.REDUX.GET_SUMMARY_INCOMES_LOADING',
  },
  saga: {
    ADD_KANTONG: 'INCOMES.SAGA.ADD_KANTONG',
    ADD_INCOMES: 'INCOMES.SAGA.ADD_INCOMES',
    GET_INCOMES: 'INCOMES.SAGA.GET_INCOMES',
    GET_SUMMARY_INCOMES: 'INCOMES.SAGA.GET_SUMMARY_INCOMES',
  },
}

export default types