const types = {
  redux: {
    GET_INCOMES_SUCCESS: 'EXPENSES.REDUX.GET_INCOMES_SUCCESS',
    GET_INCOMES_FAILURE: 'EXPENSES.REDUX.GET_INCOMES_FAILURE',
    GET_INCOMES_LOADING: 'EXPENSES.REDUX.GET_INCOMES_LOADING',

    POST_ADD_KANTONG_SUCCESS: 'EXPENSES.REDUX.POST_ADD_KANTONG_SUCCESS',
    POST_ADD_KANTONG_FAILURE: 'EXPENSES.REDUX.POST_ADD_KANTONG_FAILURE',
    POST_ADD_KANTONG_LOADING: 'EXPENSES.REDUX.POST_ADD_KANTONG_LOADING', 

    GET_SUMMARY_INCOMES_SUCCESS: 'EXPENSES.REDUX.GET_SUMMARY_INCOMES_SUCCESS',
    GET_SUMMARY_INCOMES_FAILURE: 'EXPENSES.REDUX.GET_SUMMARY_INCOMES_FAILURE',
    GET_SUMMARY_INCOMES_LOADING: 'EXPENSES.REDUX.GET_SUMMARY_INCOMES_LOADING',
  },
  saga: {
    ADD_KANTONG: 'EXPENSES.SAGA.ADD_KANTONG',
    GET_INCOMES: 'EXPENSES.SAGA.GET_INCOMES',
    GET_SUMMARY_INCOMES: 'EXPENSES.SAGA.GET_SUMMARY_INCOMES',
  },
}

export default types