const types = {
  redux: {
    GET_INCOMES_SUCCESS: 'EXPENSES.REDUX.GET_INCOMES_SUCCESS',
    GET_INCOMES_FAILURE: 'EXPENSES.REDUX.GET_INCOMES_FAILURE',
    GET_INCOMES_LOADING: 'EXPENSES.REDUX.GET_INCOMES_LOADING',
  },
  saga: {

  },
}

export default types