import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { createTheme, ThemeProvider, styled } from '@mui/material/styles'
import { wrapper } from 'store'
import { theme } from 'components/style'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>My Finance Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  )
}

export default wrapper.withRedux(MyApp)
