import type { NextPage } from 'next'
import Head from 'next/head'
import { AppTitle } from 'components/style'
import TotalSaldoComponent from 'components/TotalSaldoComponent'
import Box from '@mui/material/Box'
import TabKantong from 'components/TabKantong'
import BannerPengeluaran from 'components/BannerPengeluaran'
import { useEffect } from 'react'
import ACTIONS from 'store/registerActions'
import { useDispatch, useSelector } from 'react-redux'

const Home: NextPage = () => {
  const dispatch = useDispatch()
  const { summaryIncomes } = useSelector((state: any) => state.incomes)


  useEffect(() => {
    dispatch(ACTIONS.incomes.getSummaryIncomes())
  }, [])

  const listKantong = summaryIncomes.filter((item: any) => item.id !== 'total')

  return (
    <Box pt="24px" pb="72px" px="12px" sx={{ minHeight: "100vh", position: 'relative' }}>
      <Head>
        <title>My Finance Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppTitle mb="62px">
        <h3>My Finance Application</h3>
      </AppTitle>

      <TotalSaldoComponent />
      <TabKantong list={listKantong} />
      <BannerPengeluaran />
    </Box>
  )
}

export default Home
