import type { NextPage } from 'next'
import Head from 'next/head'
import { AppTitle } from 'components/style'
import TotalSaldoComponent from 'components/TotalSaldoComponent'
import Box from '@mui/material/Box'
import TabKantong from 'components/TabKantong'
import BannerPengeluaran from 'components/BannerPengeluaran'

const Home: NextPage = () => {
  return (
    <Box px="12px" sx={{ minHeight: "100vh" }}>
      <Head>
        <title>My Finance Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppTitle pt="20px" mb="62px">
        <h3>My Finance Application</h3>
      </AppTitle>

      <TotalSaldoComponent />
      <TabKantong />
      <BannerPengeluaran />
    </Box>
  )
}

export default Home
