import type { NextPage } from 'next'
import Head from 'next/head'
import { AppTitle } from 'components/style'
import TotalSaldoComponent from 'components/TotalSaldoComponent'
import Box from '@mui/material/Box'
import TabKantong from 'components/TabKantong'
import BannerPengeluaran from 'components/BannerPengeluaran'
import { useEffect, useState } from 'react'
import ACTIONS from 'store/registerActions'
import { useDispatch, useSelector } from 'react-redux'
// import { db } from 'services/firebase-client'
// import { collection, onSnapshot } from 'firebase/firestore'

const Home: NextPage = () => {
  const dispatch = useDispatch()
  const { incomes, kantong } = useSelector((state: any) => state.incomes)

  const [listKantong, setListKantong] = useState<Array<any>>([])
  const [totalSaldo, setTotalSaldo] = useState(0)

  // const kantongRef = collection(db, 'kantong')

  useEffect(() => {
    // const unsubscribe = onSnapshot(kantongRef, (querySnapshot) => {
    //   dispatch(ACTIONS.incomes.getSummaryIncomes())
    //   console.log('listen')
    // });
    // dispatch(ACTIONS.incomes.getSummaryIncomes())
    dispatch(ACTIONS.incomes.getIncomes())
    dispatch(ACTIONS.incomes.getKantong())
  }, [])

  useEffect(() => {
    let _listKantong: Array<any> = []
    kantong.forEach((item: any) => {
      let total: number = 0
      incomes.forEach((income: any) => {
        if (income.kantong.id === item.id) {
          total += income.value
        }
      })
      _listKantong.push({
        ...item,
        amount: total,
      })
    })
    setListKantong(_listKantong)
  }, [kantong, incomes])

  useEffect(() => {
    let totalSaldo: number = 0
    incomes.forEach((income: any) => {
      totalSaldo += income.value
    })
    setTotalSaldo(totalSaldo)
  }, [incomes])

  return (
    <Box pt="24px" pb="72px" px="12px" sx={{ minHeight: "100vh", position: 'relative' }}>
      <Head>
        <title>My Finance Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppTitle mb="62px">
        <h3>My Finance Application</h3>
      </AppTitle>

      <TotalSaldoComponent amount={totalSaldo} />
      <TabKantong list={listKantong} />
      <BannerPengeluaran />
    </Box>
  )
}

export default Home
